---
# For use with pre-commit.
# See usage instructions at https://pre-commit.com
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
