---
- name: run bigdft simple test
  command: "make C.check"
  args:
    chdir: "{{ bigdft_topdir }}/build/bigdft/tests/DFT/cubic"
    creates: "{{ bigdft_topdir }}/build/bigdft/tests/DFT/cubic/C-test"
