- name: run bigdft simple test
  command: "make C.in"
  become: true
  args:
    chdir: "{{ bigdft_topdir }}/build/bigdft/tests/DFT/cubic"
    creates: "{{ bigdft_topdir }}/build/bigdft/tests/DFT/cubic/C-test"

- name: Remove test log on re-compile
  when: bigdft_make.changed
  file:
    path: "{{ bigdft_topdir }}/build/bigdft/tests/DFT/cubic/C-test/log.yaml"
    state: absent

- name: run test suite
  command: "mpirun --allow-run-as-root --oversubscribe --mca btl_vader_single_copy_mechanism none -np {{ bigdft_test_cpus }} bigdft"
  become: true
  args:
    chdir: "{{ bigdft_topdir }}/build/bigdft/tests/DFT/cubic/C-test"
    creates: "{{ bigdft_topdir }}/build/bigdft/tests/DFT/cubic/C-test/log.yaml"
