- hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
  - name: Update apt cache.
    apt: update_cache=yes cache_valid_time=3600
    when: ansible_os_family == 'Debian'

  roles:
  - role: marvel-nccr.bigdft
